version: "3.8"
services:
  mysql_server:
    container_name: mysql_server
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: secretG6
      MYSQL_DATABASE: hotels_db
    networks:
      - db-net
    ports:
      - 3306:3306
    restart: always
  web:
    depends_on:
      - mysql_server
    build: .
    environment:
      MYSQL_HOST: mysql_server
    networks:
      - db-net
    ports:
      - "4000:4000"
    restart: on-failure
networks:
  db-net: