version: "3.8"
services:
  book_mysql_server:
    container_name: book_mysql_server
    build: ./docker/db
    environment:
      MYSQL_ROOT_PASSWORD: secretG6
      MYSQL_DATABASE: bookings_db
      MYSQL_TCP_PORT: 3307
    networks:
      - db-net
    ports:
      - 3307:3306
    restart: always
  book_web:
    depends_on:
      - book_mysql_server
    build: .
    environment:
      MYSQL_HOST_BOOK: book_mysql_server
      BOOK_PORT: '3307'
    networks:
      - db-net
    ports:
      - "3000:3000"
    restart: on-failure
networks:
    db-net: